project: 
  type: website
  
website: 
  page-navigation: true
  title: "from _quarto.yml" 
  site-url: "https://tomasrei.github.io/econometrics.companion/" 
  repo-url: https://github.com/tomasrei/econometrics.companion
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This text is controlled by _quarto.yml ❤️"
    left: "&copy; This text is controlled by _quarto.yml"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/tomasrei
        text: "Github repo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome page
      - section: my_scripts/intro_monte_income.md
        contents: 
          - my_scripts/montecarlo_income.qmd
          - my_scripts/markdown.md
      - section: 
        contents:
          - my_scripts/did/001_did_intro.qmd



format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
