---
title: "Monte Carlo simulations for the curious"
subtitle: "Whatch estimators converge - and more!"
---

## Test text {#welcome}

This is a link: [Quarto](https://quarto.org).

<!---
Here is how you put a comment in!
--->

## Qs

I wonder what controls the arrows at the bottom of this page. Probably in the yml.


The _site folder contains the html-files:

+ index.html

+ learning-more.html

+ transition-from-rmarkdown.html

I think Index is the 1st link on the LHS and the other two are the last two links. Where is Explore and setup and Quarto workflows from?

A: I found a index.qmd that contains the text in "Quarto workflows" in the quarto-workflows folder.


## Improving the github workflow

Now it installs the rpackages everytime. But you can cache them
[stackoverflow](https://stackoverflow.com/questions/59538441/does-github-action-install-the-same-packages-each-time).

:::{.callout-note}
As you modify `_quarto.yml`, the most important thing to know is that **spacing matters**. Pay attention to whether text is indented by one, two, four, or other spaces, and make sure you follow it; if your site is not looking as expected it is likely a silent error in your YAML. Some text editors like RStudio provide debugging support for YAML and are highly recommended to save you time and heartache.



